### PR TITLE
Rename index.js to app.js

### PR DESCRIPTION
**Pull request by gorio**

### CODE REVIEW

**Comment by smishra2** [comment]
Hi @gorio can you explain why you want to make this change?

**Comment by vineet-sinha** [comment]
@smishra2 - The documentation and `package.json` file reference an app.js file. This code also does not run locally or on Heroku.

**Comment by vineet-sinha** [comment]
My recommendation is that instead of renaming the file as suggested above - we could instead created a new index.js and bring back the capability something along the lines as:
```javascript
let express = require('express');
let bodyParser = require('body-parser');
let action = require('./index.js');

let app = express();
app.set('port', (process.env.PORT || 8080));
app.use(bodyParser.json({type: 'application/json'}));

app.post('/', function (req, res) {
  console.log('handle post');
  action.sayNumber(req, res);
});

let server = app.listen(app.get('port'), function () {
  console.log('App listening on port %s', server.address().port);
  console.log('Press Ctrl+C to quit.');
});
```

**Comment by smishra2** [comment]
Hi @vineet-sinha  and @gorio , you were right to catch a couple errors in the package.json and documentation. We've updated these. Keep in mind, this sample was re-written as a Cloud Function, rather than an Express app, so we no longer recommend using an app.js, unless you prefer. In that case, you can rewrite the sample as you've outlined. Hope that helps!

**Comment by vineet-sinha** [comment]
@smishra2 - Sounds good. You might want to an express sample since many people are not (yet) running their services on Google Cloud. Additionally, this needs to get updated: https://developers.google.com/actions/tools/fulfillment-hosting#deploying_to_heroku

**Pull request closed without merging**
